In [39]:


from ucimlrepo import fetch_ucirepo 
from tabulate import tabulate
import pandas as pd

# fetch dataset 
energy_efficiency = fetch_ucirepo (id=242) 
  
# data (as pandas dataframes) 
X = energy_efficiency.data.features 
y = energy_efficiency.data.targets 
  
# metadata 
#print(energy_efficiency.metadata) 
  
# variable information 
print(energy_efficiency.variables) 
x = 0

# Check if 'df' is a DataFrame
if isinstance(energy_efficiency.variables, pd.DataFrame):
#if isinstance(x, pd.DataFrame):
    print("The object 'df' is a DataFrame.")
else:
    print("The object 'df' is NOT a DataFrame.")


  name     role        type demographic                description units  \
0   X1  Feature  Continuous        None       Relative Compactness  None   
1   X2  Feature  Continuous        None               Surface Area  None   
2   X3  Feature  Continuous        None                  Wall Area  None   
3   X4  Feature  Continuous        None                  Roof Area  None   
4   X5  Feature  Continuous        None             Overall Height  None   
5   X6  Feature     Integer        None                Orientation  None   
6   X7  Feature  Continuous        None               Glazing Area  None   
7   X8  Feature     Integer        None  Glazing Area Distribution  None   
8   Y1   Target  Continuous        None               Heating Load  None   
9   Y2   Target  Continuous        None               Cooling Load  None   

  missing_values  
0             no  
1             no  
2             no  
3             no  
4             no  
5             no  
6             no  
7          

In [40]:
energy_efficiency.variables

name     role        type demographic                description units  \
0   X1  Feature  Continuous        None       Relative Compactness  None   
1   X2  Feature  Continuous        None               Surface Area  None   
2   X3  Feature  Continuous        None                  Wall Area  None   
3   X4  Feature  Continuous        None                  Roof Area  None   
4   X5  Feature  Continuous        None             Overall Height  None   
5   X6  Feature     Integer        None                Orientation  None   
6   X7  Feature  Continuous        None               Glazing Area  None   
7   X8  Feature     Integer        None  Glazing Area Distribution  None   
8   Y1   Target  Continuous        None               Heating Load  None   
9   Y2   Target  Continuous        None               Cooling Load  None   

  missing_values  
0             no  
1             no  
2             no  
3             no  
4             no  
5             no  
6             no  
7             no  
8             no  
9             no

In [41]:
energy_efficiency.data.features 

X1     X2     X3      X4   X5  X6   X7  X8
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0
..    ...    ...    ...     ...  ...  ..  ...  ..
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5

[768 rows x 8 columns]

In [42]:
energy_efficiency.variables

name     role        type demographic                description units  \
0   X1  Feature  Continuous        None       Relative Compactness  None   
1   X2  Feature  Continuous        None               Surface Area  None   
2   X3  Feature  Continuous        None                  Wall Area  None   
3   X4  Feature  Continuous        None                  Roof Area  None   
4   X5  Feature  Continuous        None             Overall Height  None   
5   X6  Feature     Integer        None                Orientation  None   
6   X7  Feature  Continuous        None               Glazing Area  None   
7   X8  Feature     Integer        None  Glazing Area Distribution  None   
8   Y1   Target  Continuous        None               Heating Load  None   
9   Y2   Target  Continuous        None               Cooling Load  None   

  missing_values  
0             no  
1             no  
2             no  
3             no  
4             no  
5             no  
6             no  
7             no  
8             no  
9             no

In [43]:

explanatory_var = ["Relative Compactness", "Surface Area", "Wall Area", "Roof Area", "Overall Height", "Orientation", "Glazing Area", "Glazing Area Distribution"]
energy_efficiency.data.features.columns  = ["Relative Compactness", "Surface Area", "Wall Area", "Roof Area", "Overall Height", "Orientation", "Glazing Area", "Glazing Area Distribution"]
energy_efficiency.data.features
#X = energy_efficiency[features_names]
#y = energy_efficiency[target_variable]


Relative Compactness  Surface Area  Wall Area  Roof Area  Overall Height  \
0                    0.98         514.5      294.0     110.25             7.0   
1                    0.98         514.5      294.0     110.25             7.0   
2                    0.98         514.5      294.0     110.25             7.0   
3                    0.98         514.5      294.0     110.25             7.0   
4                    0.90         563.5      318.5     122.50             7.0   
..                    ...           ...        ...        ...             ...   
763                  0.64         784.0      343.0     220.50             3.5   
764                  0.62         808.5      367.5     220.50             3.5   
765                  0.62         808.5      367.5     220.50             3.5   
766                  0.62         808.5      367.5     220.50             3.5   
767                  0.62         808.5      367.5     220.50             3.5   

     Orientation  Glazing Area  Glazing Area Distribution  
0              2           0.0                          0  
1              3           0.0                          0  
2              4           0.0                          0  
3              5           0.0                          0  
4              2           0.0                          0  
..           ...           ...                        ...  
763            5           0.4                          5  
764            2           0.4                          5  
765            3           0.4                          5  
766            4           0.4                          5  
767            5           0.4                          5  

[768 rows x 8 columns]

In [44]:
energy_efficiency.variables

name     role        type demographic                description units  \
0   X1  Feature  Continuous        None       Relative Compactness  None   
1   X2  Feature  Continuous        None               Surface Area  None   
2   X3  Feature  Continuous        None                  Wall Area  None   
3   X4  Feature  Continuous        None                  Roof Area  None   
4   X5  Feature  Continuous        None             Overall Height  None   
5   X6  Feature     Integer        None                Orientation  None   
6   X7  Feature  Continuous        None               Glazing Area  None   
7   X8  Feature     Integer        None  Glazing Area Distribution  None   
8   Y1   Target  Continuous        None               Heating Load  None   
9   Y2   Target  Continuous        None               Cooling Load  None   

  missing_values  
0             no  
1             no  
2             no  
3             no  
4             no  
5             no  
6             no  
7             no  
8             no  
9             no

In [45]:
from sklearn.model_selection import train_test_split
import random

random_seed = 32
random.seed(random_seed)
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.2, random_state=random_seed)

In [46]:
print(X.shape)
print(y.shape)
print(y_test.shape)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(768, 8)
(768, 2)
(154, 2)
(614, 8)
(614, 2)
(154, 8)
(154, 2)


In [47]:
categorical_variables = ["Orientation"]

numerical_variables = [var for var in explanatory_var if var not in categorical_variables]

print (numerical_variables)

print (categorical_variables)


['Relative Compactness', 'Surface Area', 'Wall Area', 'Roof Area', 'Overall Height', 'Glazing Area', 'Glazing Area Distribution']
['Orientation']


In [ ]:

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean"))
    ("scaler", StandardScaler())
])

preprocessing_pipeline = ColumnTransformer([
    ("num_pipeline", numerical_pipeline, numerical_variables),
    ("encoder", OneHotEncoder(), categorical_variables)
])

#X_train_transformed = preprocessing_pipeline.fit_transform(X_train)
#X_train_transformed


#print(X_train_transformed.shape)


In [59]:
#pd.DataFrame (X_train_transformed)


In [50]:
pd.DataFrame (X_train)

Relative Compactness  Surface Area  Wall Area  Roof Area  Overall Height  \
196                  0.90         563.5      318.5     122.50             7.0   
22                   0.76         661.5      416.5     122.50             7.0   
137                  0.64         784.0      343.0     220.50             3.5   
469                  0.66         759.5      318.5     220.50             3.5   
627                  0.98         514.5      294.0     110.25             7.0   
..                    ...           ...        ...        ...             ...   
403                  0.79         637.0      343.0     147.00             7.0   
88                   0.64         784.0      343.0     220.50             3.5   
310                  0.76         661.5      416.5     122.50             7.0   
555                  0.74         686.0      245.0     220.50             3.5   
727                  0.90         563.5      318.5     122.50             7.0   

     Orientation  Glazing Area  Glazing Area Distribution  
196            2          0.10                          4  
22             4          0.00                          0  
137            3          0.10                          2  
469            3          0.25                          4  
627            5          0.40                          3  
..           ...           ...                        ...  
403            5          0.25                          3  
88             2          0.10                          1  
310            4          0.25                          1  
555            5          0.40                          1  
727            5          0.40                          5  

[614 rows x 8 columns]

In [51]:
from sklearn.linear_model import LinearRegression

regressor_pipeline = Pipeline([
    ("preprocessing", preprocessing_pipeline),
    ("regressor", LinearRegression())
])

In [52]:
regressor_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  ['Relative Compactness',
                                                   'Surface Area', 'Wall Area',
                                                   'Roof Area',
                                                   'Overall Height',
                                                   'Glazing Area',
                                                   'Glazing Area '
                                                   'Distribution']),
                                                 ('encoder', OneHotEncoder(),
                                                  ['Orientation'])])),
                ('regressor', LinearRegression())])

In [53]:
regressor_pipeline.score(X_train, y_train)

0.9002831168263717

In [54]:
regressor_pipeline.score(X_test, y_test)

0.9059275270660962

In [55]:
predictions_train = regressor_pipeline.predict(X_train)
predictions_train

array([[27.99539495, 30.2454927 ],
       [31.37039495, 33.7767427 ],
       [12.12039495, 14.8079927 ],
       ...,
       [36.46414495, 37.4954927 ],
       [13.69825724, 16.93533099],
       [33.92481974, 35.06033099]])

In [56]:
predictions_test = regressor_pipeline.predict(X_train)
predictions_test = regressor_pipeline.predict(X_test)

predictions_test

array([[35.58914495, 36.4017427 ],
       [40.12794474, 40.52908099],
       [37.32351995, 37.5579927 ],
       [17.05789495, 18.6829927 ],
       [25.04981974, 28.12283099],
       [32.63601995, 33.8392427 ],
       [35.57351995, 36.4329927 ],
       [ 9.71414495, 13.1517427 ],
       [13.10476995, 15.7142427 ],
       [ 9.55789495, 13.3861177 ],
       [18.90164495, 20.0579927 ],
       [24.91726995, 27.2142427 ],
       [33.04226995, 33.5267427 ],
       [28.22976995, 30.9954927 ],
       [10.66726995, 14.0267427 ],
       [24.81544474, 28.02908099],
       [30.19851995, 31.6204927 ],
       [29.69851995, 31.5892427 ],
       [16.00320745, 17.6517427 ],
       [25.66726995, 27.9329927 ],
       [33.62039495, 34.4017427 ],
       [12.89383245, 15.8079927 ],
       [27.20606974, 30.84158099],
       [16.05789495, 18.0579927 ],
       [11.78419474, 15.52908099],
       [16.33106974, 18.49783099],
       [30.16726995, 31.9329927 ],
       [35.33914495, 36.3392427 ],
       [14.41726995,

In [57]:
from sklearn.metrics import mean_squared_error as mse
import numpy as np 

print (np.sqrt(mse(y_train, predictions_train)))
print (np.sqrt(mse(y_test, predictions_test)))


3.046102442405912
3.118605335871328


In [60]:
#3.041742935312052
#3.1158761198333655
y_train

Y1     Y2
196  29.06  29.34
22   24.77  29.79
137  15.18  19.34
469  13.00  15.59
627  32.75  34.00
..     ...    ...
403  39.83  36.87
88   15.41  19.37
310  36.91  37.45
555  14.55  17.25
727  35.24  37.27

[614 rows x 2 columns]

In [61]:
regressor_pipeline.named_steps["regressor"].coef_

array([[-6.21261611e+01,  2.55155354e+11, -2.55155354e+11,
        -5.10310708e+11,  4.20883345e+00,  1.94101579e+01,
         2.31194421e-01, -2.67922904e+08, -2.67922905e+08,
        -2.67922905e+08, -2.67922905e+08],
       [-6.70936944e+01,  4.85739941e+11, -4.85739941e+11,
        -9.71479882e+11,  4.01373129e+00,  1.43721458e+01,
         1.15426780e-01, -5.10045562e+08, -5.10045563e+08,
        -5.10045562e+08, -5.10045562e+08]])